### ISSUE TITLE
most of the code is messed up.

### ISSUE THREAD

**Issue by liami98** [nishi7409/ClanLabsV2-OpenSourced#4]
For example, every await function you have it throws an error of 

await rbx.cookieLogin(`${config.rblxCookie}`)
^^^^^

SyntaxError: await is only valid in async function

Also now that Discord.js had now updated you must add cache to things like bot.channels.get, it now must be bot.channels.cache.get()

**Comment by longsawk0102** [comment]
fun fact of the day: this project isn't completed yet! wow damn that's crazy!! i wonder why it says "This repository is an active devlopment for V3"
